repos:
  - repo: https://github.com/python-poetry/poetry
    rev: "1.6.0"
    hooks:
      - id: poetry-check
      - id: poetry-lock
  - repo: https://github.com/psf/black
    rev: 23.9.1
    hooks:
    - id: black
  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.0.291
    hooks:
    - id: ruff
      args: [--exit-non-zero-on-fix]
